### ISSUE TITLE
Foundry logout feature

### ISSUE THREAD

**Issue by maoo** [finos/legend#12]
Provide the ability to logout via /foundry app, and across all other applications (ie execution, sdlc, ...)

Work around: delete all cookies assigned to the /foundry host

**Comment by maoo** [comment]
Hey @gs-bracej , any update on this?

**Comment by gs-bracej** [comment]
Yes, this is done internally. It is waiting for us to do our next external push, which is expected to be Jan 20, when we're code-complete on the other promised features.

**Comment by brooklynrob** [comment]
@gs-bracej @maoo This is issue is still open and also still in the "in progress" queue on the kanban (https://github.com/orgs/finos/projects/5) -- does this need to be resolved before open the pilot instance?

**Comment by gs-bracej** [comment]
It's just a nice-to-have, not a blocker for the pilot. The current version of Studio has a logout URL https://alloy.finos.org/studio/log.in/logout, but not a link to it in the GUI, which we'll put in the next release.

**Comment by maoo** [comment]
Thanks @gs-bracej ! I'm going to put the item on hold for now, waiting for the next release. TY!

**Comment by maoo** [comment]
@gs-bracej - any update on this?

**Comment by gs-bracej** [comment]
No, thanks for the reminder!

**Comment by gs-bracej** [comment]
I spent a little time on this today, and I'm having some trouble working out what the right behavior should be.

We have a logout feature in Studio now, which you can see by going to http://alloy.finos.org/studio/log.in/logout. It correctly logs you out of Alloy and destroys your session cookie, however when you then access Studio you get redirected to GitLab which seamlessly recreates your cookie and sends you back to Studio. The net effect is that after logging out Studio just logs you back in again and it doesn't appear as if you've logged out at all.

I considered making Studio also call the GitLab logout URL, but if you do that the same thing happens - GitLab starts the GitHub SSO flow, and assuming you're still logged into GitHub everything flows through again and you end up back in Studio.

We could make Studio also log you out of github.com, but that seems a step too far. So I guess my question is, what do we expect logout to actually do? If we expect it to send you back to a login page we may have made the SSO flow a bit too seamless.

Thoughts @maoo @brooklynrob ?

**Comment by maoo** [comment]
James,
Thanks for the update.

I believe there is still value to reset connection cookies, while keeping
the current sso setup on github. Today I helped a user's issue resolution
by requesting him to cancel cookies and try again.

What if we simply call the feature "reset authentication" or something
along those lines? Best would be to have a hint that describes what the
feature does (maybe when hovering on the button? ).

Wdyt?

Thanks,
  Mao

**Comment by beekemarie** [comment]
Should be moved to the Studio backlog.
