### ISSUE TITLE
Discuss how to manage GA releases

### ISSUE THREAD

**Issue by maoo** [finos/legend#131]
Right now, Alloy is composed by a list of modules that have independent release cycles; for example, the UI module could be on version 1.0.4 and modeling module could be 1.0.6 . 

There is no concept of GA release (ie, Alloy 1.0, which includes UI 1.0.4 and modeling 1.0.6) and we were debating whether it was something needed.

From a technical standpoint, there is no need for a GA release, and the absence of it allows modules (and teams) to have a leaner way to develop software (granted that code is constantly tested across all versions, see https://github.com/finos/alloy/issues/130).

We wanted to keep track of this discussion to understand what's the opinion of the rest of the team.

**Comment by brooklynrob** [comment]
[As discussed on June 9 meeting] Assuming we don't insist on GA releases, next question would how do we brand releases -- i.e., how would we brand a release that is, say, Alloy 1.0.1, UI 1.03, and modeling 1.04. Key question is how do we brand new releases - suggestion is that we do roll-up releases vs headline releases. 

Suggestion made to also make sure we have release notes to describe what is in a release.

**Comment by maoo** [comment]
I think that we're good for the go-live, yes (removed label)

But I'd like to discuss this before the next big release, as I believe that there should be a bit of strategy on how to cut general releases, regardless of the modular nature of the project.

**Comment by agitana** [comment]
@beekemarie @epsstan FYI this is what we discussed last week, let's use this issue to discuss next steps, starting from
https://legend.finos.org/docs/advanced/legend-docker-image

**Comment by beekemarie** [comment]
@agitana @maoo can we close this issue?

**Comment by maoo** [comment]
Yes, see https://legend.finos.org/releases
