### ISSUE TITLE
Re-name Alloy to New Name in PURE code

### ISSUE THREAD

**Issue by brooklynrob** [finos/legend#140]
Re-name Alloy to New Name in PURE code

**Comment by aitana16** [comment]
@gs-bracej @brooklynrob there are still occurrences of "Alloy" in the Engine code. Is this a blocker for open sourcing?

**Comment by gs-bracej** [comment]
As discussed, this isn't a blocker, just a tech debt item.

**Comment by gs-bracej** [comment]
Completed.
