### ISSUE TITLE
User guide: how to run your own on premise version

### ISSUE THREAD

**Issue by aitana16** [finos/legend#143]
User guide: how to run your own on premise version

**Comment by knighan** [comment]
Any progress on the how to instal/run guide to kick the tyres ? wondering what it would take to install Alloy Modelling Environment in AWS

**Comment by brooklynrob** [comment]
Hey @knighan. Between Goldman and FINOS we hope to add documentation on how to launch your own instance of Alloy in the cloud, whether that's @AWS, @GoogleCloudPlatform, @OpenShift, @Azure, @IBM-Cloud, etc,  around or soon after the open sourcing of the code itself (tentatively scheduled for late September). As to specifics regarding a particular cloud provider, I think we're half-expecting one or a couple of the providers will create a "quick-launch"/one-click mechanism for Alloy, with associated documentation, but really that's up to them.

**Comment by brooklynrob** [comment]
Moving this to post wave 1 to-do list. I do expect this will be a high priority item that the community will be interested in and looking for in the docs.

**Comment by aitana16** [comment]
See the installation guide created by the Goldman Sachs Legend team at https://legend.finos.org/docs/getting-started/installation-guide
