### ISSUE TITLE
GS consumes Alloy modules released under FINOS

### ISSUE THREAD

**Issue by aitana16** [finos/legend#144]
- [x] Shared (JAR/Maven)
- [ ] Studio (NPM)
- [ ] SDLC (JAR/Maven)
- [ ] Engine (JAR/Maven)
- [ ] Pure (JAR/Maven)
- [ ] Studio (Docker)
- [ ] Engine (Docker)

**Comment by brooklynrob** [comment]
@maoo @pierredebelen @gs-bracej Can this be closed? Or shall we wait until the build work is done for all 5 modules?

**Comment by maoo** [comment]
Not entirely, there's quite a long list of assets to consume, will update the issue description.

**Comment by brooklynrob** [comment]
@maoo @pierredebelen @gs-bracej this should still be open pending engine and pure?

**Comment by maoo** [comment]
@gs-bracej - I believe there are more Legend modules that are now consumed by GS, right? Could you please provide an update? TY!

**Comment by gs-bracej** [comment]
All modules are now being consumed by GS as Jars/NPM images. Since the Docker part is captured in #247 I vote to close this.

**Comment by maoo** [comment]
Awesome, thank you!
