### ISSUE TITLE
Open Source Legend Engine code

### ISSUE THREAD

**Issue by aitana16** [finos/legend#146]
Depends on
-[  ] [Phase 2: M2.1b – Execution Code Uplift](https://github.com/finos/alloy/milestone/10)
-[  ] [Test build and deploy works in open source environment for Engine](https://github.com/finos/alloy/issues/133)

**Comment by brooklynrob** [comment]
Depends on
[ ] [Phase 2: M2.1b – Execution Code Uplift](https://github.com/finos/alloy/milestone/10)
[ ] [Test build and deploy works in open source environment for Engine](https://github.com/finos/alloy/issues/133)

**Comment by brooklynrob** [comment]
Completed when github repo is switched from private to public

**Comment by brooklynrob** [comment]
Dupe of https://github.com/finos/alloy/issues/233?

**Comment by maoo** [comment]
https://github.com/finos/legend-engine
