### ISSUE TITLE
Open Source Legend Studio Code

### ISSUE THREAD

**Issue by aitana16** [finos/legend#147]
Depends on
-[ ] [Phase 2: M2.1a – Studio Code Uplift](https://github.com/finos/alloy/milestone/9)
-[ ] [Test build and deploy works in open source environment for Studio](https://github.com/finos/alloy/issues/132)

**Comment by brooklynrob** [comment]
Dependent on successful conclusion of https://github.com/finos/alloy/issues/132

**Comment by brooklynrob** [comment]
Completed when github repo is switched from private to public

**Comment by brooklynrob** [comment]
@maoo @pierredebelen @gs-bracej With repos now switched to public, I think this (and the similar issues for the other modules) can be closed.
