### ISSUE TITLE
Define new code release process beyond GSOSS 

### ISSUE THREAD

**Issue by aitana16** [finos/legend#149]
Define new code release process beyond GSOSS, specifically to answer
- [x] Will developers still need to be added to the GS CCLA individually?
- [x] Any changes to the per-PR review process to be done?

**Comment by brooklynrob** [comment]
Likely will happen after open sourcing per @beekemarie at 2020.7.28 check-in call.

**Comment by brooklynrob** [comment]
For wave go-live, GS-OSS process is still being used, including existing CCLA process. Will evaluate how that is working and scales and more internal GS developers are use the external FINOS OSS infrastructure.

**Comment by aitana16** [comment]
done
