### ISSUE TITLE
GS Developer Orientations Session (#1)

### ISSUE THREAD

**Issue by maoo** [finos/legend#187]
This will be an approx 2 hours session to orient GS developers on all things related to FINOS project infrastructure; agenda below.

- FINOS Project Governance
  - Rights and responsibilities of a project maintainer
    - Will, knowledge and authority to manage a FINOS (hosted) project
  - FINOS Code of conduct
- FINOS Project Lifecycle
  - Lifecycle landscape
  - States and transitions
- ODP Training
  - The FINOS GitHub Organization
    - GitHub Repos VS FINOS projects
    - GitHub FINOS Members - validate membership is public
    - GitHub Kanban Boards
    - Issues and PR mentions
  - FINOS (GitHub) teams, roles and permissions
    - Who can do what
    - Team and permissions validation
  - FINOS Project Landscape
    - Validate project information
  - Release process
    - Dry run of a potential/scheduled release
  - Continuous Integration
    - GitHub Actions (recommended)
    - Secrets management
  - Security automation
    - Responsible disclosure for security vulnerabilities (if applicable)
    - WhiteSource for GitHub.com integration
  - Documentation website
    - Custom configuration
    - Update workflow (direct and via Pull Request)
  - Meetings management
    - Review how to manage meetings minutes
    - Review how to track attendance

**Comment by brooklynrob** [comment]
For the Developer Onboarding session to be maximally effective, https://github.com/finos/alloy/issues/186 should be completed such that all developers are authorized and set up to contribute to a FINOS repository

**Comment by brooklynrob** [comment]
@beekemarie @pierredebelen @gs-bracej Let's discuss when/if/how to get this scheduled on our 2020-10-13 check-in.

**Comment by brooklynrob** [comment]
Scheduled for 9am ET 10/20. CC @beekemarie @maoo

**Comment by aitana16** [comment]
done in October 2020
