### ISSUE TITLE
Setup email Alerts for Alloy Pilot

### ISSUE THREAD

**Issue by maoo** [finos/legend#200]
Everytime that an outofmemory occurs, the FINOS/GS team needs to be notified, as it may be the indication that the system is getting overloaded and it's time to scale up/out.

**Comment by brooklynrob** [comment]
@maoo Is this something @AWS may need to help us with? Or more an application layer issue/optimization? Or just time to scale up?

**Comment by maoo** [comment]
No, this is a system configuration. It's on me.

**Comment by maoo** [comment]
@gs-bracej - I just created a CloudWatch Metric Filter, following [https://dinfratechsource.com/2018/11/12/how-to-use-cloudwatch-to-generate-alerts-from-logs/](https://dinfratechsource.com/2018/11/12/how-to-use-cloudwatch-to-generate-alerts-from-logs/), which applies to the `/aws/containerinsights/AlloyClusterCLI/application` Log Group (see screenshot)

<img width="585" alt="Screenshot 2020-09-29 at 16 26 49" src="https://user-images.githubusercontent.com/327285/94571827-a69f9100-0270-11eb-8ea1-4c8117be64de.png">

Could you please:
1. Review the settings
2. Generate an `ERROR` entry in the application logs, so we can test what happens

Thanks!

**Comment by gs-bracej** [comment]
It certainly makes sense, don't we already have this alert though? I'm sure we've done this previously and I am receiving emails for errors.

**Comment by maoo** [comment]
I did remember that too. Could you please forward me one of these emails please, so I can track and document AWS configuration?

Thanks!

**Comment by maoo** [comment]
Here's how logging is configured:
- Cloudwatch defines a Subscription filter with pattern `{ $.log = "*HTTP/1.1\" 500 *" }` and points to a lambda function (ARN)
- The lambda function below sends an email alert every time the subscription fires a log event

```
const zlib = require('zlib');
const aws = require('aws-sdk');
const ses = new aws.SES({region: 'us-east-1'});

exports.handler = (event, context, callback) => {
    const payload = Buffer.from(event.awslogs.data, 'base64');
    const parsed = JSON.parse(zlib.gunzipSync(payload).toString('utf8'));
    console.log('Decoded payload:', JSON.stringify(parsed));
    
    const logText = parsed.logEvents.map(e => JSON.parse(e.message))
        .map(l => l.kubernetes.container_name + ': ' + l.log).join('\r\n');
    
    var params = {
        Destination: {
            ToAddresses: ["infra@finos.org"]
        },
        Message: {
            Body: {
                Text: { Data: logText }
            },
            Subject: { Data: "Alloy Error Alert" }
        },
        Source: "maoo@finos.org"
    };

    console.log(`Successfully processed ${parsed.logEvents.length} log events for Alloy.`);

    ses.sendEmail(params, function (err, data) {
        if (err) {
            console.log(err);
            context.fail(err);
        } else {
            console.log(data);
            context.succeed(event);
        }
        callback(null, {err: err, data: data});
    }).send();
};
```

@gs-bracej - could you please review if the filter pattern is good enough to intercept all issues? If so, feel free to close this issue. TY!

**Comment by gs-bracej** [comment]
Hmmmm. This reports when a user experiences a 500 response, which isn't the only way a server can fail. I would say we change change it to capture "Exception" but that would produce a lot of false positives.

@pierredebelen What do you think? How can we capture genuine issues?

**Comment by maoo** [comment]
Did some further investigation on logs, as I'd like to close this issue sooner rather than later.

- fluentd - only found logs with `[info]` prefix, so I suppose we could add an alert to catch on `[error]`
- execution - using logs from the latest Pilot downtime, I noticed that logs have a `INFO` level when logging exceptions; could it be changed to `ERROR`, so that we can grep on that term and send out email notifications?

I would suggest the following:
1. Checking the entire codebase for `catch` logic and make sure that it includes a `logger.error` statement, where applicable of course
2. Add a CloudWatch alert to catch `[error]` and `ERROR` terms. The latter may generate some false positives, which we'll tweak on the way

@gs-bracej @pierredebelen - WDYT?

**Comment by gs-bracej** [comment]
Totally agree, but as you say this will need a bit of cleanup in the code. Good first issue for the community?

**Comment by aitana16** [comment]
Working with @maoo he suggested to update the title and description of the issue around "improving application logging"

**Comment by maoo** [comment]
Just updated the filter to `{ $.log = "*HTTP/1.1\" 500 *" || $.log = "*ERROR*" || $.log = "*error*" || $.log = "*Exception*" }`, let's see how many false positives we get.

I think we're good to go with this, assuming we're certain that it's still working.

@gs-bracej - let me know if you have the chance to generate a 500 on studio, or any other error/exception? TY!

**Comment by maoo** [comment]
@gs-bracej @pierredebelen - FYI - updated regexp to `{ $.log = "*HTTP/1.1\" 500 *" || $.log = "*ERROR*" || $.log = "*error*" || $.log = "*Exception*" }` , as I got a lot of notifications for website 404s.

**Comment by brooklynrob** [comment]
Is the really a "good first issue" @maoo and @gs-bracej ?

**Comment by maoo** [comment]
> Is the really a "good first issue" @maoo and @gs-bracej ?

Yes, but there's too much history in this issue; I created https://github.com/finos/legend/issues/292 (which is a "good first issue", closing this one.
