### ISSUE TITLE
Extend gitlab.alloy.finos.org license to support 1000 users

### ISSUE THREAD

**Issue by maoo** [finos/legend#210]
We currently are limited to 100 users, but we expect to surpass that limit after the open sourcing.

@nuritzi @gl-jayo - could you please send us a license that supports 200 or more users?

**Comment by brooklynrob** [comment]
Bumping this in light of our recent support conversations. I think we should plan for 1000 seats. @nuritzi @maoo

**Comment by aitana16** [comment]
done
