### ISSUE TITLE
09 09 2020 Alloy Commodity Reference Data WG

### ISSUE THREAD

**Issue by astonGS** [finos/legend#213]
## Date
08 19 2020 - 16:00 BST

## Approve past meeting minutes
Minutes Approved

## Agenda
- Agree on fixedLeg (forwardPayout) format
- Agree on naming conventions of payout types
- Finalize Model Proposal

Discussion Points:
- Group agreed on the the fixedLeg representation with the ForwardPayout object & also agreed that removing the FX element for the proposal is the correct approach. The FX element is being refactored in a separate initiative & the Commodities proposal captures what the end state should look like. 
- Different naming conventions were discussed & the group agreed that this is not critical for the submission and review for ISDA ARC. Submission names that will be used are:
     - ObservationPayout : Rename of AssetPayout and superType to both CommodityPayout and EquityPayout
     - CommodityPayout: Captures commodity specific terms and opted for in preference of AveragePayout for review purpose. 

Additional point was discussed around constraints in the model and that these would be a day 2 item to be addressed. Constraints based on the underlier type (future vs published price) have a dependency on a more robust underlier model.

Group agreed to submit the model in studio for review. 

### WebEx info
- Meeting link: https://finos.webex.com/finos/j.php?MTID=me57eb4b2609b694befaaaf62c107f7e0
- Meeting number: 667 751 733
- Password: M4SiJxsth47
- Join by video system: Dial 667751733@finos.webex.com. You can also dial 173.243.2.68 and enter your meeting number.
- Join by phone: +1-415-655-0003 US Toll | +44-20319-88141 UK Toll| Access code: 667 751 733

**Comment by aitana16** [comment]
hi!

**Comment by mdemarzio** [comment]
present

**Comment by TSanborn-ISDA** [comment]
here
