### ISSUE TITLE
Define Support Model for Alloy

### ISSUE THREAD

**Issue by brooklynrob** [finos/legend#225]
Define Support Model, including SLAs and escalation processes for Alloy, considering needs of roles including:

- [ ] Modelers on shared instanced (alloy.finos.org/studio)
- [ ] Developers making commits/pull requests
   - [ ] Internal GS (e.g,. developers who heretofore were relying solely on internal GS CI/CD and processes)
   - [ ] External developers 
- [ ] Systems engineers standing up their own instances of Alloy

**Comment by mindthegab** [comment]
My proposal:

1. For modelers of the shared instance, FINOS should provide first level support and as second level to the alloy-maintainers@ (if that’s created) list or via GitHub issues to the project if it’s a code issue.

2. Internal GS developers: first level would be internal, second level would be the project maintainers (again via mailing list or GitHub)

3. External developers go to alloy-general@ as first resort and second line to maintainers (again via mailing list or GitHub)

4. Engineers standing up Alloy - same as external developers at point 3

My 0.02$

**Comment by finos-admin** [comment]
**Modelers:** 
- 1st line: FINOS via help@finos.org (@mcleo-d is responsible /cc @toshaellison) - target (internal) SLA: 24h / 48h
- 2nd line: if it's deemed to be a product bug (technical), then open issue in relevant alloy-* repo. If it's deemed to be an issue with the model itself (functional), then open issue in the respective gitlab repo for the models.

**Internal GS Developers**
- 1st line: they contact James / Pierre. 
- 2nd line: open issue in the relevant alloy-* repo

**External Developers/ Engineers standing up Alloy**
- Raise issue in the relevant alloy-* repo 
- We can re-evaluate later if we need different channels / queues / a dev mailing list 

/cc @gs-bracej @pierredebelen @beekemarie what do you guys think? Sounds about right as support model?

**Comment by brooklynrob** [comment]
Per discussion on 2020.9.29, regarding support from the FINOS team to the core GS team (e.g., @pierredebelen, @beekemarie, @gs-bracej), esp. during the next few weeks during launch prep:
- For updates, including "good to go on next step" updates (e.g., GS telling FINOS it has concluded https://github.com/finos/alloy/issues/188 and is ready to move to https://github.com/finos/alloy/issues/184), use the Github issue comments (e.g., here), ideally tagging "whose got next" and referencing the next issue in the sequence
- For requests that are more of a support nature - e.g., adding a developer to a security group so they have access to a repo - use help@finos.org

**Comment by brooklynrob** [comment]
@pierredebelen @beekemarie @gs-bracej Any further feedback that you wanted to share on the overall support model for Alloy after the open sourcing milestone (i.e., what's defined above)? (CC @aitana16 @mindthegab @maoo @mcleo-d)

**Comment by gs-bracej** [comment]
This seems reasonable to me!

**Comment by brooklynrob** [comment]
As discussed on our 2020-10-7 weekly check-in, let's also establish and document our escalation scenarios with/for
- GitLab (CC @nuritzi)
- @GitHub (CC @jbjonesjr)
- @AWS

These plans should include:
- Point of Contact when help is needed
- Availbility
- SLAs
- Likely/common support scenarios

**Comment by brooklynrob** [comment]
Let's give ourselves at least 2 weeks post launch to assess how support and escalations are going until we close this isse. CC @nuritzi @jbjonesjr @github @aws @pierredebelen @aitana16 @beekemarie @gs-bracej @maoo

**Comment by maoo** [comment]
@brooklynrob - given that the time has passed, I wonder if we can close this issue now. Please let me know if there's anything else left to be done. TY!

**Comment by aitana16** [comment]
Reviving this thread due to the Nov 20th Studio downtime episode: 
We (@maoo and I) will follow up based on https://github.com/finos/legend/issues/225#issuecomment-700286598 as soon as the post mortem is completed. 
Regarding https://github.com/finos/legend/issues/225#issuecomment-704975458, our  suggestion is to create a "3rd line" in the support model described above, that is delivered by API providers (GitHub, GitLab, AWS) that are part of Legend.
FINOS will work with those providers in order to enable this support model.
/ cc @gs-bracej @beekemarie @pierredebelen

**Comment by nuritzi** [comment]
@aitana16 @maoo I didn't see a support ticket come through about the downtime, just an announcement about the downtime via the FINOS mailing list afterwards. Let me know if I missed something, or if we need to revisit anything specifically for the GitLab portion of this.

**Comment by agitana** [comment]
Closing this issue as there's agreement on the support model as per https://github.com/finos/legend/issues/225#issuecomment-700800446 and https://github.com/finos/legend/issues/225#issuecomment-703802084. 3rd level escalation scenarios with API providers are managed by FINOS and GS:

**Modelers on the shared instance**
- 1st line: FINOS via help@finos.org 
- 2nd line: if it's deemed to be a product bug (technical), then open issue in relevant legend-* repo. If it's deemed to be an issue with the model itself (functional), then open issue in the respective GitLab repo for the models.

**Internal GS Developers**
- 1st line: they contact James / Pierre.
- 2nd line: open issue in the relevant legend-* repo

**External Developers/ Engineers standing up Alloy**
- Raise issue in the relevant legend-* repo

/ cc @maoo
