### ISSUE TITLE
Update GS CCLA Schedule A with new description

### ISSUE THREAD

**Issue by brooklynrob** [finos/legend#226]
Update GS CCLA Schedule A with new description provide by @pierredebelen

**Comment by mindthegab** [comment]
Do we really need this? We did not in the past.

Meaning, if the contribution of the code happens with a ID that is covered under schedule B (eg Pierre or James), then we have not required modifications of the schedule A.

Schedule A is used for “first time code contribution” from a firm firm for which the CCLA is not on file.

Unless @swinslow has a different interpretation or you folks discuss this already, I vote to close this one.

**Comment by agitana** [comment]
moving this to the internal FINOS team priorities board
