### ISSUE TITLE
FINOS Code Scans, Checks, Validation - Alloy Engine/Execution

### ISSUE THREAD

**Issue by aitana16** [finos/legend#232]
This is dependent on https://github.com/finos/alloy/issues/231 being completed (i.e., the code being uploaded)

## Engine
- [ ] FINOS Security Vulnerability Check
- [ ] FINOS Legal/License Scans
- [ ] Apply FINOS Project Blueprint

**Comment by aitana16** [comment]
Working with @maoo - he confirmed there's still one CVE pending (see GitHub issues)

**Comment by brooklynrob** [comment]
@maoo Can this be updated? Or still working on the CVE?

**Comment by maoo** [comment]
Still working on 1 CVE on engine. PR is ready to merge, and it seems to fix the issue. I've asked @gs-bracej to review. /CC @pierredebelen

**Comment by brooklynrob** [comment]
Done per @maoo on 2020.10.19
