### ISSUE TITLE
[Action Required] Amazon EKS Kubernetes 1.14 Deprecation - Update Your Cluster

### ISSUE THREAD

**Issue by maoo** [finos/legend#241]
Hello,

Amazon EKS has deprecated Kubernetes version 1.14 and this version will no longer be supported on December 8, 2020. On this day, you will no longer be able to create new 1.14 clusters and all EKS clusters running Kubernetes version 1.14 will be updated to the latest available platform version of Kubernetes version 1.15.

You are receiving this message because you currently have 1 or more EKS clusters running with Kubernetes version 1.14, listed below:

arn:aws:eks:us-east-1:730743682544:cluster/AlloyClusterCLI

We recommend that you update your 1.14 clusters to Kubernetes version 1.15 as soon as possible.

To learn more on Kubernetes version support, see the Amazon EKS service documentation [1].
For instructions on how to update your cluster(s), see the Amazon EKS service documentation [2].

[1] [https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html)
[2] [https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html](https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html)

**Comment by beekemarie** [comment]
@maoo can we close this issue?

**Comment by maoo** [comment]
Yes!
