### ISSUE TITLE
Test release and consumption of Docker images

### ISSUE THREAD

**Issue by maoo** [finos/legend#247]
We will be using https://hub.docker.com/u/finos to host images.

Tasks:
- [x] Define images that need to be uploaded - @gs-bracej
  - [x] Studio
  - [x] SDLC
  - [x] Engine
- [x] Update GitHub Actions to push images when build happens on master (and configure secrets)
- Test image consumption - see https://github.com/finos/legend/issues/144
- [ ] Build and publish documentation on how to use images (may require a new/dedicated issue)

**Comment by maoo** [comment]
@gs-bracej - could you please confirm that docker images that we should publish right now are Studio, SDLC and Engine? TY!

**Comment by gs-bracej** [comment]
Confirmed! The beta site is using the public legend-studio Docker image, so that definitely works. Let's move forward and create images for the other two.

**Comment by maoo** [comment]
> Confirmed! The beta site is using the public legend-studio Docker image, so that definitely works. Let's move forward and create images for the other two.

Awesome! In theory the build should already be there, it's just a matter of running `mvn install -Pdocker`. Who's best suited to test this for SDLC and Engine? As soon as the build is confirmed to work, I can try the actions to automatically publish on Docker Hub.

**Comment by gs-bracej** [comment]
Sorry you've lost me. What does mvn install -Pdocker do?

**Comment by maoo** [comment]
Sorry for the lack of context.

`mvn install -Pdocker` will build an image locally by parsing the `Dockerfile` resolved in the root folder of the repo.
`mvn deploy -Pdocker` will push the image to `hub.docker.com/u/finos`.

Assuming that the `install` works, I can easily test the deployment, by installing the secrets on GitHub.

More info on https://github.com/finos/finos-parent-pom/#docker-integration

**Comment by gs-bracej** [comment]
Got it, thanks! Will work on it for SDLC first, then do Engine.

**Comment by maoo** [comment]
This is now done! See https://github.com/finos/legend/tree/master/installers/aws-docker . Thanks @epsstan !
