### ISSUE TITLE
Add code owners and test

### ISSUE THREAD

**Issue by maoo** [finos/legend#248]
Each repo should include a `.github/CODEOWNERS` file that define code owners, or approvers, for each project, which are part of (what is going to be) the default branch protection configuration - see https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/about-code-owners

Repos to update
- [x] Shared
- [x] Studio
- [x] SDLC
- [x] PURE
- [x] Engine

**Comment by gs-bracej** [comment]
PRs:
https://github.com/finos/legend-shared/pull/54
https://github.com/finos/legend-studio/pull/24
https://github.com/finos/legend-sdlc/pull/30
https://github.com/finos/legend-pure/pull/25
https://github.com/finos/legend-engine/pull/29

**Comment by aitana16** [comment]
done
