### ISSUE TITLE
Legend Informational/Overview Training Video

### ISSUE THREAD

**Issue by brooklynrob** [finos/legend#26]
Produce Alloy Informational/Overview video:
- [ ] Identify topics 
- [ ] Write script 
- [ ] Do story board 
- [ ] Produce Video 
- [ ] Post and distribute video
   - [ ] Add video/link to video in microsite
   - [ ] Add video/link to video in www.finos.org/alloy

**Comment by maoo** [comment]
@brooklynrob - any update on this?

**Comment by brooklynrob** [comment]
@beekemarie Is this in progress now at this point? Have the topics, scripts, and story board been done now? Any help needed?

**Comment by brooklynrob** [comment]
In production within GS

**Comment by aitana16** [comment]
done, see https://github.com/finos/legend/blob/master/README.md#review-the-existing-materials
