### ISSUE TITLE
Grammar mistake? --> "Opportunities are sheer endless"

### ISSUE THREAD

**Issue by brooklynrob** [finos/legend#262]
"Opportunities are sheer endless" on the home page (website/static/index.html) reads strange.

Perhaps revise to “There is a sheer endless number of ways to put Legend to use ... "

What do you think @nicoalba @beekemarie?

<img width="620" alt="Screen Shot 2020-10-17 at 6 11 47 PM" src="https://user-images.githubusercontent.com/2136904/96354479-29b04c00-10a5-11eb-95d0-5fd910c1eee5.png">

**Comment by gs-bracej** [comment]
This has been fixed.

**Comment by brooklynrob** [comment]
cool thanks
