### ISSUE TITLE
Add mention and description of shared instance on docs site

### ISSUE THREAD

**Issue by brooklynrob** [finos/legend#266]
I think there should be a mention of the [shared instance](https://legend.finos.org/studio) and how to get an account on the docs site, perhaps in the get-involved section and/or in the installation page (as a "in the meantime" or "alternatively" option)

**Comment by beekemarie** [comment]
@aitana16 can we close this out? We mention the shared instance in our contribute section https://legend.finos.org/docs/getting-started/contribute-to-legend
