### ISSUE TITLE
Change GitLab Group Path

### ISSUE THREAD

**Issue by brooklynrob** [finos/legend#273]
While the legend-project in gitlab has the new name, the `group path` is still `alloy-pilot`. I think we should change that, either to `legend-pilot` or, perhaps more accurately now, `legend-shared` (and in that the case the name should be updated too) to better reflect that the models in this project are shared Legend models

Name:
![image](https://user-images.githubusercontent.com/2136904/96497562-e0810900-1218-11eb-8eca-91e41283f42c.png)

Group setting: 
![image](https://user-images.githubusercontent.com/2136904/96497543-d959fb00-1218-11eb-9add-efc11d48a823.png)

After this is done, we should also address, https://github.com/finos/legend/issues/252

For time, being the links to the Gitlab repos in the README are 404-ing as I had anticipated the `group path` would be legend-pilot. Once this change is made we could check/update the README.

**Comment by maoo** [comment]
Fixed, thanks for spotting @brooklynrob
