### ISSUE TITLE
Legend projects ReadMe.md Roadmap link broken

### ISSUE THREAD

**Issue by gcampbell-sl** [finos/legend#277]
### Steps to Reproduce:
 1. Visit the ReadMe of the following Legend projects and scroll down to the Roadmap section header.
- https://github.com/finos/legend-pure
- https://github.com/finos/legend-sdlc
- https://github.com/finos/legend-engine
- https://github.com/finos/legend-shared

 2. Follow the link to https://legend.finos.org/docs/roadmap and arrive at a 404 Page not found page.

### Expected Result:
Either a Roadmap page, or as the (https://github.com/finos/legend-studio) page has:
"Visit our [home page](https://legend.finos.org/) to know more about the roadmap."

### Actual Result:
[404 Page not found](https://legend.finos.org/docs/roadmap)

### Environment:
NA

### Additional Context:
NA

**Comment by maoo** [comment]
Thanks for the issue @gcampbell-sl ! I'll send out a PR right away. For what I can see, the roadmap is currently on https://github.com/finos/legend#roadmap .

@beekemarie @brooklynrob - could you please confirm?

**Comment by beekemarie** [comment]
@maoo yes, correct. You can link to https://github.com/finos/legend#roadmap. You'll do the fix?

**Comment by maoo** [comment]
@beekemarie - If we want to publish the roadmap on legend.finos.org in the future, I'd suggest to create the missing page (on legend.finos.org/docs/roadmap) , and just link to https://github.com/finos/legend#roadmap . This way, when we want to migrate, we simply have to update one page, not all links. WDYT?

**Comment by beekemarie** [comment]
@maoo - we prefer not to have a detailed roadmap page on our doc page for now. Having it as part of the readme.md should be sufficient for now as we also have a high-level version of the roadmap directly on the main page under legend.finos.org.

**Comment by maoo** [comment]
@beekemarie 👍 

@gs-bracej @akphi - could you please update the READMEs across all repos to replace https://legend.finos.org/docs/roadmap with https://github.com/finos/legend#roadmap ?

**Comment by akphi** [comment]
@maoo @gs-bracej yeah I can take care of those

**Comment by akphi** [comment]
@maoo @beekemarie @gs-bracej @pierredebelen 
Can you guys review and merge these in? I fixed all doc links as well

https://github.com/finos/legend-studio/pull/26
https://github.com/finos/legend-sdlc/pull/36
https://github.com/finos/legend-engine/pull/41
https://github.com/finos/legend-pure/pull/33
https://github.com/finos/legend-shared/pull/59
https://github.com/finos/legend/pull/280

**Comment by maoo** [comment]
All PRs reviewed; @beekemarie @akphi - feel free to merge, I don't want to take [your credits](https://metrics.finos.org/goto/df1ef86aa25a9b8856317923bb74e8c7) 😄

**Comment by akphi** [comment]
@maoo looks like https://github.com/finos/legend-shared/pull/59 got some problem with getting the CLA check result

**Comment by akphi** [comment]
@maoo shall we close this one then?
