### ISSUE TITLE
Cube healthcheck returns a 404

### ISSUE THREAD

**Issue by maoo** [finos/legend#279]
Check https://legend.finos.org/cube/admin/healthcheck

It used to work until October 16. @gs-bracej - any idea what happened?

**Comment by gs-bracej** [comment]
Sorry this is my fault! I forgot we had Cube deployed, since it's not used in the current stack. The version we have is super old and Cube wasn't included in the current open sourced code, I say let's just turn the healthcheck off for now and we can resurrect it when we get the Cube code out.

**Comment by maoo** [comment]
Thanks @gs-bracej ,  I removed the entry from the status dashboard.
