### ISSUE TITLE
Change Group name from "legend-pilot" to "legend-shared"

### ISSUE THREAD

**Issue by brooklynrob** [finos/legend#282]
Following completion of https://github.com/finos/legend/issues/273 (change of group-name, to match new name), I wanted to suggest we take the next step and change the group-name from "legend-pilot" to "legend-shared" in GitLab. The pilot has ended and so too, I think, has the semantic value of "legend-pilot". How about we go just with "legend-shared", which represents better what these models are -- shared, public models built in and with Legend.

**Comment by brooklynrob** [comment]
@pierredebelen @beekemarie @gs-bracej -- any thoughts on this? Seems to me like "legend-shared" would be more logical name  for our collection of model repos in GitLab.

**Comment by gs-bracej** [comment]
I think that would be confused with the legend-shared code repo we have. I would also be concerned about it becoming a dumping ground for models without clear ownership. Maybe the thing to do would be to have an ISDA group for CDM and similar models, a FINOS-FO group for models owned by FINOS, and a Scratch group for things that shouldn't be used in production?

**Comment by brooklynrob** [comment]
Good point @gs-bracej. It can't be named "legend-shared"

I like the idea different groups for different purposes. I especially like the implication that the name and group-name could/should match the name of the overarching FINOS project (or external standards body/initiative) associated with the work. What do others think?

Also a reminder of the loosely related discussion at https://github.com/finos/community/issues/64 about on-going modeling efforts that may leverage the shared Legend instance.
