### ISSUE TITLE
Use RSS feed from Hubspot Legend Update Blog (on www.finos.org) to populate Microsite Blog/News Items

### ISSUE THREAD

**Issue by brooklynrob** [finos/legend#29]
# Background
Visitors to the FINOS website will soon have the ability to sign-up for PURE/Alloy updates (e.g., dates for demos, new models available, schedule down times, etc.) on the FINOS website, including on https://www.finos.org/pure-alloy. They will receive these updates by email.

These updates are also, behind the scenes, an RSS feed.

# Feature Request
Use this stream of PURE/Alloy updates from FINOS Hubspot to populate the blog/news section of the Docusaurus powered microsite. 

# Down the Road...
Stretch goal would be to make it possible for these posts from the RSS feed to be interspersed amongst other blog updates that might be made directly as .MD files within Docusaurus but that is firmly in the nice to have category right now.

**Comment by maoo** [comment]
If I understand the requirement correctly, there should be a "live news feed" box in the homepage of purealloy.finos.org , listing an RSS feed published by http://finos.org .

I suppose the following info should be visualized for each entry:
- title
- date
- first 250 chars of post content

Couldn't find anything ready for Docusaurus, but I [found a simple way to do this in React](https://blog.usejournal.com/build-a-simple-twitter-like-feed-using-reactjs-181b67b648a1), which could be added to the purealloy Docusaurus code (or - better - defining a Docusaurus plugin that could be reused across different Docusaurus projects.

@brooklynrob , before moving forward, could you please confirm the requirements listed above?

@rikoe - as you played with Docusaurus in the past, did you stumble on a similar feature, by any chance?

TY!

**Comment by brooklynrob** [comment]
@maoo yes, it's sort of React 101 -- take a RSS feed and show the posts in a site. That's the idea, yes.

I think it's title, date, author (potentially -- may default to "FINOS"), and ideally the full post such that they don't need to bounce back to finos.org to read the post -- we want to keep them in microsite not push them back to finos.org. 

I think it would be helpful to see a sample of the RSS feed out of hubspot before we lock on the fields to display and how long.
