### ISSUE TITLE
Update README to reflect that installation information has been added to the doc sites (legend.finos.org)

### ISSUE THREAD

**Issue by brooklynrob** [finos/legend#295]
1. Delete "(Coming Soon; Information on running and installing your own instance of Legend, locallly, on premise, or in a cloud provider such as AWS, Azure, OpenShift, Google, etc.)"

2. Replace it with link(s) to what exists (what has now/since be created) on the docs site (e.g., https://legend.finos.org/docs/getting-started/installation-guide) with additional context with what documentation may be pending (w links to the issue that document those docs requirements)

3. Include in the README a reminder that people can/should suggest areas for documentation improvement.

**Comment by aitana16** [comment]
PR submitted, see https://github.com/finos/legend/pull/298
