### ISSUE TITLE
Expand Legend Overview on https://developer.gs.com/

### ISSUE THREAD

**Issue by brooklynrob** [finos/legend#32]
Currently there is a short PURE/Alloy on https://developer.gs.com/ at https://developer.gs.com/docs/products/.

Once the microsite is ready to go, a longer overview of PURE/Alloy will be added to https://developer.gs.com/docs/products/ as well some additional content on FINOS.

**Comment by brooklynrob** [comment]
Let us know if/as there is an update on this, @beekemarie

**Comment by brooklynrob** [comment]
Currently there is a link to 1) PURE and 2) Alloy on https://developer.gs.com/docs/  
![image](https://user-images.githubusercontent.com/2136904/96426846-cbca5400-11cb-11eb-8458-d8f8f86e184b.png)

**Comment by brooklynrob** [comment]
Any update on getting this updated?

![image](https://user-images.githubusercontent.com/2136904/97615938-4c6e2900-19f2-11eb-82a9-e239e7cb18f6.png)

**Comment by beekemarie** [comment]
@brooklynrob Yes, I requested the necessary changes with the developer.gs dev team and they are working on it right now in the current sprint. Should be fixed within the next week or so.
