### ISSUE TITLE
What is the Legend-PURE language? 

### ISSUE THREAD

**Issue by agitana** [finos/legend#320]

**Comment by beekemarie** [comment]
The Legend PURE language is a functional language which allows for the creation of domain models and functions that operate on those models. Domain models capture the important information about concepts in the problem domain including their relationship while functions allow for operations to be specified in terms of model and language elements. Legend allows for the mapping of domain model elements to data stores, the system will compile functions to queries on those stores. The language is currently used to model all sorts of different business domains, including but not limited to financial services functions such as risk assessment, reporting, or human resources.

**Comment by agitana** [comment]
thank you @beekemarie!
