### ISSUE TITLE
What diagramming functionality does Legend Studio currently support and what's on the roadmap for future enhancements?

### ISSUE THREAD

**Issue by agitana** [finos/legend#322]

**Comment by beekemarie** [comment]
Currently we support visualizations of models built in the editor as well as some simple drag & drop functionality (e.g. adding classes to the diagram, re-arranging/re-sizing boxes, ...). We do have small improvements in the pipeline (e.g. color options of boxes) but would encourage the community to suggest improvements to the diagramming feature that they would think will be helpful. Please open up GitHub issues with your suggestions and feel free to start contributing to those as well.
