### ISSUE TITLE
What are the Git options for Legend? Can we use other git providers, like Stash? Can it run without git? 

### ISSUE THREAD

**Issue by agitana** [finos/legend#324]

**Comment by beekemarie** [comment]
GitLab is the strategic partner we chose for our Data Model SDLC in Legend. The main reason that other Git providers won’t work right now is that Legend does more than pull/push, it uses GitLab-specific APIs to create reviews, approve + merge changes, probe the list of available projects etc. Other Git providers likely have analogues to these features and if so it would be possible to add support, but it would certainly require some development effort.
