### ISSUE TITLE
Can you elaborate why a Mongodb instance is needed when installing Legend on prem? 

### ISSUE THREAD

**Issue by agitana** [finos/legend#325]

**Comment by beekemarie** [comment]
Legend uses MongoDB for a number of purposes, but the crucial one when it is deployed is for synchronizing session state between the different microservices. When running locally we don’t synchronize state as you usually only run one service at once, allowing us to simplify the steps somewhat. For developing more complex features it is sometimes necessary to setup MongoDB for local development too.
