### ISSUE TITLE
How has Legend been used to standardize data models in the industry? 

### ISSUE THREAD

**Issue by agitana** [finos/legend#334]

**Comment by beekemarie** [comment]
As Legend Studio was being open sourced, delivering value for the industry was important and therefore connecting with ISDA and the CDM was a natural expansion of already established engagement. This led to two working groups being set up as part of the pilot – both committed code to the golden source of the CDM:
• FX Options: the Averaging Model developed by the FX Options workstream was proposed back to ISDA, and has been approved and released in the CDM (see 2.82.8). 
• Commodity Reference Data: especially in the context of a Fixed vs Float swap, including defining a payout model which has been approved and released in the CDM. 
Legend is also being used in the FINOS Reference Currency workstream building a standard model for currencies and the related data. 
There are a few other projects that are being explored and will be proposed through FINOS in the coming months – please look out for proposals here: https://github.com/finos/community/issues/new/choose and please do provide other challenges that may be tackled through collaborative modelling in the same place.
