### ISSUE TITLE
What is the approval process for proposed changes to models maintained in the public instance of Legend (e.g. ISDA's CDM)? 

### ISSUE THREAD

**Issue by agitana** [finos/legend#335]

**Comment by beekemarie** [comment]
Legend currently leverages Gitlab SDLC for approving and merging data model changes. Code review is initiated through Studio and changes are then able to be viewed in GitLab before approval. This means, model changes can be completely managed in the Studio UI. Generally, we encourage users working on data models to customize their own approval process leveraging out of the box GitLab functionality. For the CDM specifically, the ISDA ARC offer governance and review of changes before being able to commit back to the golden source in Rosetta.
