### ISSUE TITLE
What other use cases beside the ISDA CDM does Legend currently cover? 

### ISSUE THREAD

**Issue by agitana** [finos/legend#338]

**Comment by beekemarie** [comment]
Internally at Goldman Sachs we use Legend across many divisions and use cases. For example, we rely heavily on data models for our regulatory reporting, human resource management and Derivatives processing. Externally, Legend Studio is also being used to standardize and map currency data/schemas to create a currency reference database as part of the FINOS-industry Securities Reference Data Project. The benefit of Legend and Studio in particular is that it allows engineers and business experts to group together in the design of data to solve many business use cases.
