### ISSUE TITLE
What is the current list of FINOS projects that use Legend, and how does one get involved/join? 

### ISSUE THREAD

**Issue by agitana** [finos/legend#339]

**Comment by beekemarie** [comment]
https://landscape.finos.org/ - a breadth of areas that FINOS are involved in across the open source environment in financial markets specific projects we feel are most relevant in the standardization discussions:
• Financial Objects: CDM expansion (e.g. commodities payout, lifecycle events)
• Regulation Innovation SIG – tbc on specific challenge to be tackled
• Securities Reference Data – Currency model
