### ISSUE TITLE
Why should I use Legend?

### ISSUE THREAD

**Issue by agitana** [finos/legend#341]

**Comment by beekemarie** [comment]
Legend provides a full, end-to-end data platform experience covering the full life cycle of data. It will help you tackle various internal data problems - including but not limited to - access to accurate, complete and timely data as well as breaking down data silos. Front and center of the data platform is the data modeling tool Legend Studio which allows engineers and non-engineers alike to describe, connect, visualize, and query data to increase efficiency and cross-divisional collaboration. As Legend is open sourced, you can also connect to a variety of industry standards (such as the CDM) in the form of data models. Please feel free to reach out by replying to this GitHub issue or by emailing legend@finos.org if you want to discuss more specific use cases with the Legend community.
