### ISSUE TITLE
How can I contribute to the Legend project?

### ISSUE THREAD

**Issue by agitana** [finos/legend#342]

**Comment by beekemarie** [comment]
There are many ways to contribute to Legend, and many of them do not involve writing any code. Here are a few ideas to get started:
1. Start using Legend Studio to provide feedback, and contribute to, existing models. Request access to the modeling instance at [https://www.finos.org/legend] and go through the Getting Started guide. Does everything work as expected? If not, we're always looking for improvements. Let us know by opening an issue
2. Contribute code
3. Help build out the documentation. Read through the Legend documentation site. If you find anything that is confusing or can be improved, submit a Pull Request.
4. Contribute issues: identify bugs, suggest new features, and provide feedback on prioritization. Look through the open issues. Provide workarounds, ask for clarification, or suggest labels. If you find an issue you would like to fix, open a pull request. Issues tagged as Good first issue are a good place to get started. Take a look at the features requested by others in the community and consider opening a pull request if you see something you want to work on.
Find more details here. [https://github.com/finos/legend/blob/master/CONTRIBUTING.md]

**Comment by agitana** [comment]
awesome, thank you @beekemarie
