### ISSUE TITLE
How can Legend expedite FinTech technology? 

### ISSUE THREAD

**Issue by agitana** [finos/legend#344]

**Comment by beekemarie** [comment]
There are two perspectives that Legend provides benefit to for fin tech technology. The first is through facilitating the collaborative development of industry standard models using Legend Studio which will help lower barriers to entry for FinTech companies. Secondly as FinTech companies provide solutions to industry challenges, Legend can be used to help participants (buy and sell side) map and integrate with their solutions for easier adoption.
