### ISSUE TITLE
Latest Release  v1.1 missing previously existing features & has many undocumented & some buggy functionalities

### ISSUE THREAD

**Issue by AJ73** [finos/legend#352]
### Steps to Reproduce:
 1.  Navigate to a model & workspace
 2. Pick a Class from the model
 3. Click on the Form text/link at the top right hand corner 

### Expected Result:
Expect to see JSOn Schema as an option to generate

### Actual Result:
**
- previously existing JSON Schema option is missing
- Also Model Loader feature wipes out the model resulting in loss of entire model
- There are so many undocumented features such as "Add a new _Connection, Runtime, Function etc._
** 

### Environment:
Version:.1.1
Build Time:2021-02-08T16:46:04-0500
Commit ID:2b175de2cff04aa299b98d8fb7d8f685fd2a8fc9
SDLC Server:/sdlc/api
Execution Server:/exec
Tracer Server:/tracer

### Additional Context:
...add any other context about the problem here. If applicable, add screenshots to help explain...

**Comment by akphi** [comment]
@AJ73 I don't think `JSONSchema` generation feature is ready yet, perhaps that's why we only released it temporarily then decided to take it back.

Regarding the `model loader (F2)`, I believe there's a check box on the top panel to say if you want to replace everything or just append to you current set of models.

As for documentation, we're in the process if vamping up the doc, so please be patient with us 🙏.

**Comment by AJ73** [comment]
Hi @akphi  really appreciate the effort and work that has gone in to making significant changes to Legend. But the JSON Schema generator has been available and well showcased since the very first release.  Also on the Model Loader the issue is the workspace gets wiped out without a refresh which is what I would expect. Maybe  UX change can be considered.

cc:@agitana ; @beekemarie ; @ffionwiggins

**Comment by akphi** [comment]
@AJ73 Regarding the model loader, I think the behaviour is to refresh the app and reloads with the models you input like below.

https://user-images.githubusercontent.com/13574879/109442316-ddd3c300-7a05-11eb-8559-814e1794888d.mov
If that's not what you get, please tell us how to reproduce that issue, but please file a separate issue over at https://github.com/finos/legend-studio/issues

**Comment by beekemarie** [comment]
Hi @AJ73! Just checking in if you were able to resolve the issue? Or is there anything else we can help you with?

**Comment by AJ73** [comment]
Hi Beeke-Marie,
Not being able to generate JSON Schema is somewhat of a show stopper for us
in Deutsche. Hoping  a new release or patch will be done for the feature to
be reinstated.

Kind Regards
Ajith

**Comment by beekemarie** [comment]
Hi Ajith! Understood! Externalizing JSON schema code gen is on our roadmap for end of Q1. So you don't need to wait long! Will post back on this thread as soon as I have an update on this.

**Comment by beekemarie** [comment]
Hi Ajith! We completed development on the JSON schema generator and currently prepping for a new release that brings this feature back. Will let you know as soon as it's available in the UI again.

**Comment by beekemarie** [comment]
Hi @AJ73! The JSON schema generator has been added back into Studio. Please let us know if you encounter any issues. Thanks!

**Comment by AJ73** [comment]
Hi Beeke-Marie,
Thank you for the note. I have briefly checked it and functionality seems to be restored. I will check the output & cross compare sometime next week when I am back from holidays.

Kind Regards
Ajith
