### ISSUE TITLE
Can you please provide the component and sub component for functionality - data classification, data discovery, data audit, data catalog, and data lineage for Legend?

### ISSUE THREAD

**Issue by VengefulTruck** [finos/legend#353]
I truly appreciate it if you could provide differences between the apache atlas and legend for the data governance project.

**Comment by beekemarie** [comment]
Hi @VengefulTruck! Thanks for reaching out. Internally, Legend includes Data Governance components but those are not yet on our open sourcing roadmap. However, with the Legend core components completely open sourced by the end of this year, you will be able to perform data exploration of modeled and un-modeled data leveraging Excel-like data manipulations (Cube), query data using business friendly terms defined in your data models (Query) and register those queries for repeated, controlled and safe usage (Services). All of those components can be considered an important part of the journey towards increased data quality & governance.
