### ISSUE TITLE
What type of metadata does Legend supports?

### ISSUE THREAD

**Issue by VengefulTruck** [finos/legend#354]
Does it support bigdata, RDBMS, etc?

**Comment by epsstan** [comment]
We are in the process of open sourcing support for RDBMS.  This allows you to model tables, schemas, joins, mapping between physical and logical models etc.

Does this answer your question ?

**Comment by epsstan** [comment]
The latest release allows you to query a relational database through legend. In fact, there is a live deep dive session about this feature tomorrow. https://www.finos.org/hosted-events/2021-07-29-legend-community-meeting-new-features-deep-dive 

Please reopen if you have specific questions.
