### ISSUE TITLE
Tracker: Deploy to FINOS environment the latest version of Legend Studio Docker image

### ISSUE THREAD

**Issue by akphi** [finos/legend#357]
@epsstan @maoo I'm opening this thread so we can keep track of the progress of this. I heard that we will get a test environment up and running soon so I'm eager to try that out. I want to note a small thing though, that Studio config has changed slightly from that of the currently working version on https://legend.finos.org/studio

So I think it looks something like this

```jsonc
// file /config/httpConfig.json
{
  // ... same as before
  "localAssetPaths": {
    "/studio/config.json" : "/config/uiConfig.json"
  },
  "uiPath": "/studio",
}

// file /config/uiConfig.json
{
  "appName": "studio",
  "env": "demo",
  "sdlc": {
    "url": "/sdlc/api"
  },
  "engine": {
    "url": "/exec/api"
  },
  "tracer": {
    "serviceName": "legend studio",
    "url": "/tracer"
  },
  "documentation": {
    "url": "https://legend.finos.org"
  },
  "options": {
    "core": {
      "TEMPORARY__disableSDLCProjectStructureSupport": true,
      "TEMPORARY__disableSDLCProjectCreation": true,
      "TEMPORARY__disableNonModelStoreSupports": true,
      "TEMPORARY__disableServiceRegistration": true
    }
  }
}

```

**Comment by maoo** [comment]
Works on the new test environment /cc @epsstan

**Comment by maoo** [comment]
@akphi , I'm getting the following error on studio now:

```
Uncaught (in promise) Assertion Error: Configration realm is missing
    at B (https://legend-acct.finos.org/studio/static/main.5bdca587.js:1:14537)
    at F (https://legend-acct.finos.org/studio/static/main.5bdca587.js:1:14586)
    at Tt.configure (https://legend-acct.finos.org/studio/static/main.5bdca587.js:1:53194)
```

Could this be related to the configuration change?

**Comment by akphi** [comment]
@maoo Yep, but this is super weird. Which Studio image are you using now? Since `0.2.5` should not have checked for the field `realm` at all as it was renamed to `env`

**Comment by akphi** [comment]
@maoo yeah, I wonder what we should do about `latest`, it's outdated and we don't really update that in our release process. What do you guys think we should do about that @pierredebelen @epsstan ?

**Comment by akphi** [comment]
@maoo I got an error when I go to this page - https://legend-acct.finos.org/studio/ Maybe we need to point the backend URLs properly in [`config.json`](https://legend-acct.finos.org/studio/config.json). Do you also deploy an instance of `engine` and `sdlc` on `acct` env?

**Comment by maoo** [comment]
> @maoo I got an error when I go to this page - https://legend-acct.finos.org/studio/ Maybe we need to point the backend URLs properly in [`config.json`](https://legend-acct.finos.org/studio/config.json).

Is the `documentation` field the backend URL? Should that be https://legend-acct.finos.org ?

> Do you also deploy an instance of `engine` and `sdlc` on `acct` env?

Yes, they're both up and running.

TY!

**Comment by maoo** [comment]
Oh, also, the `exec` url used to be `/exec`, now it's `/exec/api` ; I'm using `2.17.0` version of engine

**Comment by maoo** [comment]
yep, that worked. Thank you @akphi !!

**Comment by akphi** [comment]
@pierredebelen regarding the `latest` tag of `finos/legend-studio`. I don't think we should publish that at all, perhaps we can consider deleting it for the following reason:

1. It's simpler and we only publish version tags anyway.
2. None of our infrastructure is currently using it.
3. Other images of Legend stack (i.e. `finos/legend-sdlc-server`, `finos/legend-engine-server`) don't have that tags.

 Should we decide to delete that tag, I believe @maoo can help us with that.

Regarding testing, we need to find some time to test this out, if we're good, we should push to https://legend.finos.org/studio soon, as this is one is packed with bug fixes.

**Comment by maoo** [comment]
> Should we decide to delete that tag, I believe @maoo can help us with that.

👍 

> Regarding testing, we need to find some time to test this out, if we're good, we should push to https://legend.finos.org/studio soon, as this is one is packed with bug fixes.

I'll take care of new deployments on https://legend.finos.org/studio , just let me know when and which image versions. TY!

**Comment by epsstan** [comment]
> Regarding testing, we need to find some time to test this out, if we're good, we should push to https://legend.finos.org/studio soon, as this is one is packed with bug fixes.

@akphi I know we don't have an automated process as yet for generating release notes. But for the next FINOS "prod" release, can we publish release notes even if we have to hand write it ?

**Comment by akphi** [comment]
@epsstan I can do for Studio, not the backend though. We changed a fair bit in the backend, maybe we need to check with @pierredebelen and @beekemarie on this

**Comment by akphi** [comment]
@maoo so Pierre and I just discussed, could you help us remove the `finos/legend-studio:latest` tag from Docker Hub? Thanks!!

**Comment by maoo** [comment]
> @maoo so Pierre and I just discussed, could you help us remove the `finos/legend-studio:latest` tag from Docker Hub? Thanks!!

done.

**Comment by akphi** [comment]
I think if it looks good to you, we can deploy to FINOS prod. I'm closing this thread now!
