### ISSUE TITLE
Starting local studio instance

### ISSUE THREAD

**Issue by aamend** [finos/legend#361]
## Unauthorized pop up

Hi

I've followed all instructions to get an instance of engine + sdlc + studio running locally (OSX) against my Gitlab application.  Both engine and SDLC APIs seem to be running as expected, but starting up studio (npm start) results in "Unauthorized" and hangs.

<img width="1263" alt="Screenshot 2021-03-13 at 23 50 56" src="https://user-images.githubusercontent.com/4445837/111057757-e2fa2e80-8457-11eb-8cb0-4871f0698b1b.png">

#### SDLC API

```
http://127.0.0.1:7075/api/currentUser
{"name":"Antoine Amend","userId":"aamend"}
```

#### Engine API

```
http://127.0.0.1:9090/api/server/v1/currentUser
"(unknown)"
```

#### Studio
My studio config (packages/legend-studio-app/dev/config.json) is set as follows

```json
{
  "appName": "studio",
  "env": "local",
  "sdlc": {
    "url": "http://127.0.0.1:7075/api"
  },
  "engine": {
    "url": "http://127.0.0.1:9090/api"
  },
  "documentation": {
    "url": "https://legend.finos.org"
  }
}
```

Is there anything obvious I may be missing? Is the engine suppose to connect to my gitlab application as well (currently returning unknown user). 

Thanks in advance for some pointers in getting started

**Comment by epsstan** [comment]
When single sign on is configured correctly, Studio initiates the OAuth flow, gets a OAuath authorization token which is subsequently propagated to SDLC and Engine as a LegendSSO cookie. 

What happens if you clear your cookies ? I'll see if I can reproduce this.

**Comment by epsstan** [comment]
Can you provide the config file that you are using for engine ? Is it using the LocalKerberosClient or GitlabClient ? 

Thanks

**Comment by aamend** [comment]
Thanks Ephrim. I realized that the engine was not configured to use gitlab oauth by default, so modified it to `org.finos.legend.server.pac4j.gitlab.GitlabClient`. Although the engine authentication works (via http://127.0.0.1:9090/api/server/v1/currentUser), studio still fails with error above (unauthorized). 

```
"clients": [
      {
        "org.finos.legend.server.pac4j.gitlab.GitlabClient": {
          "name": "gitlab",
          "clientId": "XXXXXXXXXXXX",
          "secret": "XXXXXXXXXXXX",
          "discoveryUri": "https://gitlab.com/.well-known/openid-configuration",
          "scope": "openid profile"
        }
      }
    ]
```

Do you think I need to enable SSL to get this to work?

**Comment by epsstan** [comment]
@aamend SSL is not needed. The "maven" install is non standard in that Studio is run using npm's web server instead of a full backend server (i.ie like SDLC) that is able to participate in the SSO flow. 

Long story short, if you are just looking to run a local installation of Legend, the Docker compose installer is the easiest to get going.  https://github.com/finos/legend/tree/master/installers/docker-compose

**Comment by epsstan** [comment]
@aamend  The Maven installer guide has been updated with new instructions. There were some nuances with Jetty session handling that have now been addressed. See finos/legend-sdlc#138.  

I am closing this issue. Please re/open if you continue to have trouble with this.
