### ISSUE TITLE
Problems With local Installation

### ISSUE THREAD

**Issue by katchyben** [finos/legend#366]
## Bug Report
Legend Studio installation broken

### Steps to Reproduce:
 **yarn setup**

➤ YN0000: ┌ Resolution step
➤ YN0060: │ @finos/legend-studio@workspace:packages/legend-studio provides react-dom (p1bbdc) with version 17.0.1, which doesn't satisfy what react-split-pane requests
➤ YN0060: │ @finos/legend-studio@workspace:packages/legend-studio [a383a] provides react-dom (p6de42) with version 17.0.1, which doesn't satisfy what react-split-pane requests
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 561ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 2s 675ms
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 2s 168ms
➤ YN0000: Done with warnings in 5s 841ms

yarn dev
[2:34:10 PM] Starting compilation in watch mode...

<i> [webpack-dev-server] Project is running at https://127.0.0.1:3000/
<i> [webpack-dev-server] webpack output is served from /
<i> [webpack-dev-server] Content not from webpack is served from /Users/bennykatchy/legend/legend-studio/packages/legend-studio-app
<i> [webpack-dev-server] 404s will fallback to /index.html
<i> [webpack-dev-middleware] wait until bundle finished: /studio
src/index.tsx:17:24 - error TS2307: Cannot find module '@finos/legend-studio' or its corresponding type declarations.

17 import { Studio } from '@finos/legend-studio';
                          ~~~~~~~~~~~~~~~~~~~~~~

src/index.tsx:18:32 - error TS2307: Cannot find module '@finos/legend-studio-preset-dsl-text' or its corresponding type declarations.

18 import { DSLText_Preset } from '@finos/legend-studio-preset-dsl-text';
                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/index.tsx:26:11 - error TS7006: Parameter 'e' implicitly has an 'any' type.

26   .catch((e) => {
             ~

[2:34:22 PM] Found 3 errors. Watching for file changes.

webpack compiled in 8561 ms

### Environment:
Yarn version 2.4.1
Node Version v15.12.0
NPM version 7.6.3
Mac OS X 10.13.6

**Comment by akphi** [comment]
Seems like you did not run `yarn build` nor `yarn setup`

**Comment by katchyben** [comment]
I ran **_yarn setup_** and also tried **_yarn build_** but still got the following warning:
➤ YN0060: │ @finos/legend-studio@workspace:packages/legend-studio provides react-dom (p1bbdc) with version 17.0.1, which doesn't satisfy what react-split-pane requests
➤ YN0060: │ @finos/legend-studio@workspace:packages/legend-studio [a383a] provides react-dom (p6de42) with version 17.0.1, which doesn't satisfy what react-split-pane requests
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the

**Comment by akphi** [comment]
It's just a warning and expected due to a dependency using an older version of react
