### ISSUE TITLE
Is there ability to generate Sample Json files with random data?

### ISSUE THREAD

**Issue by AJ73** [finos/legend#377]
Yes LEGEND allows generation of sample data, allows modification & storage within the project  and reuse in Tests that can help with Test Driven Model development. This is done by  
1.  Creating a Mapping within LEGEND
2.  Use a Class as a source for which a test data needs to be created 
3.  Drag the Class into Execute tab at the bottom of the screen

![image](https://user-images.githubusercontent.com/7070680/112323323-97425300-8ca9-11eb-9e3c-b4b1d05fd1f7.png)

**Comment by beekemarie** [comment]
Thanks @AJ73 for posting this FAQ!
