### ISSUE TITLE
Docker with remote gitlab failing authorization

### ISSUE THREAD

**Issue by shnkax** [finos/legend#385]
### Steps to Reproduce:
1. Installed legend using docker containers and remote gitlab as per: https://github.com/finos/legend/blob/master/installers/docker-compose/legend-with-remote-gitlab/README.md#gitlab-oauth-config-setup
2. Launching legend studio fails with an "unauthorized" error. Interestingly, the gitlab redirect works fine, and the "unauthorized" URLs work just fine when accessed directly outside legend studio. Please see attached gif.

### Expected Result:
Expected studio to launch and display projects

### Actual Result:
Unauthorized

### Environment:
Docker: https://github.com/finos/legend/blob/master/installers/docker-compose/legend-with-remote-gitlab/README.md#gitlab-oauth-config-setup

### Additional Context:
Tried with both gitlab.com and self-hosted gitlab instance.
![legend_docker_auth_failure](https://user-images.githubusercontent.com/81576873/112858447-dee92600-907f-11eb-89c8-526290d22ca5.gif)

**Comment by akphi** [comment]
Did you try to look at the [troubleshooting doc](https://github.com/finos/legend/blob/master/installers/docker-compose/TROUBLESHOOTING.md#getting-unauthorized-and-401-call-to-sdlc-after-logging-into-gitlab-and-being-redirected-to-studio). Also please try to do this in an incognito window and let us know!

**Comment by shnkax** [comment]
Thank you very much! Can I suggest that you add a sentence (directly in README file) to run the studio in incognito window:

https://github.com/finos/legend/blob/master/installers/docker-compose/legend-with-remote-gitlab/README.md

`After starting the project, you can go to your browser at http://HOST_ADDRESS:8080/studio to launch Studio. ` => `After starting the project, you can go to your browser in incognito mode at http://HOST_ADDRESS:8080/studio to launch Studio. `
