### ISSUE TITLE
Model-to-model mapping execution results in PureExecutionException

### ISSUE THREAD

**Issue by shnkax** [finos/legend#387]
### Steps to Reproduce:
Trying a fairly straightforward mapping (similar to the one [here](https://legend.finos.org/docs/studio/create-model-to-model-mapping)) results in PureExecutionException

### Expected Result:
Execution works

### Actual Result:
`PureExecutionException: Execution error at (resource:/core/pure/mapping/modelToModel.pure line:166 column:17), "Match failure: JsonModelConnectionObject instanceOf JsonModelConnection"`

The error seems to be originating from here: https://github.com/finos/legend-pure/blob/1c1895e14c7bdebbde138ad0ce5e096210eac145/legend-pure-code-compiled-core/src/main/resources/core/pure/mapping/modelToModel.pure

See attached text version of the models, and a screenshot of the execution.

### Environment:
Docker: https://github.com/finos/legend/blob/master/installers/docker-compose/legend-with-remote-gitlab/README.md#gitlab-oauth-config-setup

### Additional Context:
See attachments
<img width="473" alt="model-to-model-exception" src="https://user-images.githubusercontent.com/81576873/112996516-3a77ea00-913a-11eb-80ff-a022466148eb.png">
<img width="1089" alt="model-to-model-execution-screenshot" src="https://user-images.githubusercontent.com/81576873/112996524-3b108080-913a-11eb-9631-b3e6d81b4d77.png">

**Comment by akphi** [comment]
@shnkax I think you're supposed to select at least one property in the `target` panel. Having said that, I think there's more we can do here to protect users from this case or maybe giving a better error message.

**Comment by shnkax** [comment]
Thanks @akphi .
