### ISSUE TITLE
docker-compose converts templates configuration files into directories

### ISSUE THREAD

**Issue by cheersmas** [finos/legend#390]
### Steps to Reproduce:
1. Move to directory: /legend/installers/legend-studio-dev/
2. Run docker-compose command `docker-compose ...` in the README.md

### Expected Result:
Should put right configuration files in the $BUILD_DIR as mentioned in the ./config.properties

### Actual Result:
configuration files picked from `/legend/installers/docker-compose/shared/templates/` are all converted to directories instead of files
eventually `docker-compose` runs but the container doesn't start as the configuration is missing, in fact it is a directory instead.

### Environment:
OS: Windows 10 Version	10.0.19041 Build 19041

### Additional Context:
This is an intermittent issue. Solved by pulling the project again and running the scripts.

**Comment by akphi** [comment]
@epsstan related to https://github.com/moby/moby/issues/30555 (as mentioned [here](https://stackoverflow.com/questions/42248198/how-to-mount-a-single-file-in-a-volume))

**Comment by epsstan** [comment]
> @epsstan related to [moby/moby#30555](https://github.com/moby/moby/issues/30555) (as mentioned [here](https://stackoverflow.com/questions/42248198/how-to-mount-a-single-file-in-a-volume))

So we have two issues. 1/ Bind mounting files is not portable and 2/ Bind mounts should use absolute and not relative paths.
Think we should sweep all the files into a single directory and mount that directory.

**Comment by akphi** [comment]
@epsstan I think `relative paths` is supported [in docker-compose](https://github.com/docker/cli/issues/1203#issuecomment-484445758) and [on Windows](https://stackoverflow.com/a/56588789). I can push a fix for 1/
