### ISSUE TITLE
How are you using Legend?

### ISSUE THREAD

**Issue by agitana** [finos/legend#392]
Hi Legend community! We know that several organizations (banks and non-banks) are evaluating Legend, and we are looking to surface adoption of FINOS projects (see the [FINOS FDC3 project](https://fdc3.finos.org/) as an example).

That being said, we currently aren't able to disclose the names of those organizations, feel free to comment on the issue below to let us know how you're using Legend

**Comment by epsstan** [comment]
Closing this issue as stale. Please re-open if relevant.
