### ISSUE TITLE
Trademark New Name

### ISSUE THREAD

**Issue by brooklynrob** [finos/legend#4]
FINOS to trademark new name once chosen.

Depends on choosing the name and getting the logo ID done.

**Comment by maoo** [comment]
@brooklynrob - maybe we can close this issue for the time being, given our latest conversations?

**Comment by beekemarie** [comment]
Hi @agitana! Can this issue be closed out?

**Comment by mindthegab** [comment]
@beekemarie yes absolutely, closing - we do not track legal related discussions here. Feel free to reach out to me directly if you have any questions regarding Legend trademark.
