### ISSUE TITLE
Import & Export of Data Models into Legend

### ISSUE THREAD

**Issue by beekemarie** [finos/legend#409]
Looking for some guidance on how we can import data models into Legend. Could not find any documentation around that, so was hoping someone can walk us through importing data models into Legend in different formats (json/avro/ddl/xml/ via a database connection..) from the Data Loader option/file upload via the api and possibly from different tools if there are any plugins built.

Also are there any options for exporting the data model in Legend in user friendly data format (csv,excel,pdf..)?

**Comment by AJ73** [comment]
@beekemarie we here in DB are also looking for the same. Would be great to have some docs on this.

**Comment by beekemarie** [comment]
Import – There is no plug-in built yet. Legend supports any file formats via API integration or you can copy/paste JSON schema into the UI. Noted this down as a coverage gap in our docs to be added.

Export – Legend currently supports JSON schema, AVRO and Protobuf. For this, please select “New file generation” from the Studio UI. Please note that this feature is still in beta state and we’re working on debugging. Building out more user-friendly export formats are currently not on our roadmap. But that may be a good first issue other contributors could work on?

**Comment by beekemarie** [comment]
@AJ73 Please see answer above and let me know if you have any follow up questions.

**Comment by beekemarie** [comment]
Moved this issue to the Legend FAQ wiki page. https://github.com/finos/legend/wiki/Legend-FAQs
