### ISSUE TITLE
Getting started with relational model

### ISSUE THREAD

**Issue by aamend** [finos/legend#412]
## Support for database query

Hi legend community Folks,
Does anyone know how to test connection to database from legend studio interface? I added an entity, mapping, store, connection, runtime, service without success. Appreciate if someone can point me to the right direction / studio user guide for relational support.

Right clicking to a mapping results in 

```
JdbcSQLSyntaxErrorException: Schema "FIRE" not found; SQL statement: select "root".FIRSTNAME as "pk_0", "root".FIRSTNAME as "firstName", "root".LASTNAME as "lastName" from fire.PERSON as "root" [90079-200]
```

<img width="1338" alt="Screenshot 2021-07-05 at 14 36 59" src="https://user-images.githubusercontent.com/4445837/124508801-9045d900-dd9e-11eb-99d9-9af842d52240.png">

Executing a runtime results in 

```
Can't find runtime 'fire::runtime::myruntime'
```

<img width="1334" alt="Screenshot 2021-07-05 at 14 35 24" src="https://user-images.githubusercontent.com/4445837/124508576-3e04b800-dd9e-11eb-83eb-c6ef3936534a.png">

**Comment by epsstan** [comment]
@aamend  Can you please post the grammar form of your model (switch to text mode f8) ?

The first JDBC sql error seems to be related to how you have implemented SQL generation in Pure. If you copy the SQL from the execution plan and run it directly against your database, do you get the same JDBC error ? If yes, you have a bug in your SQL generation. The error message has the schema in both upper and lower case. Are names case sensitive in your database ?

Not sure about your second error. The screen shot shows the runtime named "delta" but you also seem to be referring to "myruntime" ?

**Comment by aamend** [comment]
Thanks for getting back to me @epsstan 
The first error occurs on master branch regardless of the database connection used (H2 database results in the same SQL exception). From what I can see, my Legend env does not even try to connect to database before throwing `JdbcSQLSyntaxErrorException`. 

The second screenshot occurs when executing a runtime. The name "myRuntime" is an example here. As you can see in the screenshot, I have a runtime "delta" defined that cannot be found.

Could you advise on the right way to test connectivity to database from legend studio?

**Comment by akphi** [comment]
@aamend @epsstan I think the `Can't find runtime` is a bug in Studio - we have a fix in one of our PR https://github.com/finos/legend-studio/pull/314/commits/a42a13a71e7be44d7d36c852a4c468a82d7430bd

**Comment by aamend** [comment]
Awesome, I confirm that reverting that change did fix this issue. Thanks!
