### ISSUE TITLE
Latest release versions of Legend Codebase

### ISSUE THREAD

**Issue by venumah** [finos/legend#417]
## Support Question

Hi Team,

We are using Legend for our exploring the options of leveraging the data modelling in our project. We are using the following version since last may:

LEGEND_SDLC_IMAGE_VERSION=0.24.0
LEGEND_ENGINE_IMAGE_VERSION=2.21.0
LEGEND_STUDIO_IMAGE_VERSION=0.2.16

Can you please let us know the new features planned in Legend and is there any planned release date of the latest features.

Thanks,
Mahesh V

**Comment by venumah** [comment]
Hi @beekemarie , Any update on the latest version of the Legend images. Keen on checking the latest features which you highlighted in the Legend deep dive session.

Thanks,
Mahesh V

**Comment by beekemarie** [comment]
Hi @venumah! Thanks for reaching out! You can always see the latest released version here https://legend.finos.org/releases. We are actively working on releasing the latest feature set I demo'd last week. We will communicate releases to the FINOS shared instance via the Legend mailing list. You can subscribe to it here: legend+subscribe@finos.org. The new features I demonstrated in the deep dive session (relational mapping & query) are available both in GitHub & the FINOS shared instance. The enhanced diagram view still needs to be released. Hope this answers your question?

**Comment by venumah** [comment]
Hi @beekemarie ,

Thanks for the information. This helps.

Thanks,
Mahesh V
