### ISSUE TITLE
Mapping to multiple data sources

### ISSUE THREAD

**Issue by pierrelamy** [finos/legend#459]
Does Legend supports the mapping of one model artefact (e.g. class or enumeration) to multiple mapping sources?

My experience is that one model artefact (left side of the mapping panel) can only have one mapping source.

The work-around that I have been trying is to create one mapping object per model artefact, represent the various mapping sources on the left side of the mapping panel and the model artefact on the right side.  The obvious downside with such approach is the multiplication of mapping objects.

I would be interested to hear whether a better approach already exists, or whether there is a plan to support the ability to associate several data sources to a model artefact.

**Comment by beekemarie** [comment]
Hi @pierrelamy! Thanks for reaching out. Could @erwin-jeanlouis-gs help you with this already or is this still an open item for you?
