### ISSUE TITLE
Alias for numerical enumeration values

### ISSUE THREAD

**Issue by pierrelamy** [finos/legend#464]
### Description of Problem:
Legend doesn't support enumeration entries that start with a numerical values.  While this is perfectly understandable, this can represent a problem for supporting some of the marketplace specified values.  An example of such are the ISDA day count fractions, that include four entries which start with a numerical value: 1/1, 30E/360, 30E/360.ISDA and 30/360.

### Potential Solutions:
Create the ability to specify an alias, similarly to what has been done as part of the Rosetta DSL, which expression for such entry is specified as: `_30E_360 displayName "30E/360"`.  Presently, the Legend expression of this enumerated entry in the Rosetta DSL is missing that alias expression.

**Comment by beekemarie** [comment]
Thanks @pierrelamy! We'll look into this.

**Comment by beekemarie** [comment]
Hi @pierrelamy! @YannanGao-gs looked into adding support for numeric values in enums and the team decided not to support it. An explanation can be found here https://github.com/finos/legend-studio/issues/563. Please let us know if you have any further comments or questions?

**Comment by beekemarie** [comment]
Closing this issue per comment above.
