### ISSUE TITLE
Legend Studio fails with 401 (Unauthorized)

### ISSUE THREAD

**Issue by maoo** [finos/legend#469]
[Opening issue on behalf of Shane Morris (RBC)]

Hi! We are attempting to install Legend Studio locally so that we can begin to contribute some code. We were thinking that a good starting point would be to try some of the good first issues as recommended in the documentation. When we were attempting to install using the yarn commands, we ran into some issues. We have SDLC, Engine, Gitlab, and mongodb running in a Linux box and were planning on using this for development. We wanted to run yarn on our local machine and connect to the Linux box for the Engine and SDLC backbends. To do this we change the config.json file located at `legend-studio/packages/legend-studio-deployment/dev/config.json` to the following:

```
{
	"appName": "studio",
	"env": "local",
	"sdlc": {
		"url": "http://<linux-box-ip>:7070/api"
	},
	"engine": {
		"url": "http://<linux-box-ip>:6060/api"
	},
	"depot": {
		"url": "http://<linux-box-ip>:9090/depot/api"
	},
	"documentation": {
		"url": "https://legend.finos.org"
	}
}
```

After doing this we received the following error: (I have blocked out the Linux box IP in the console logs)

![image002](https://user-images.githubusercontent.com/327285/142379369-561f4549-5695-46ad-80d7-449ccaeada98.jpg)

We were wondering if this type of setup is possible, and why this error might be occurring.

We understand that this issue is known to be caused by SDLC and Engine not being authenticated, but we already attempted to:
1. Grab the authorization tokens from SDLC and Engine
2. Hard refresh Chrome window and delete cookies
3. Use Chrome Incognito
4. Check the api/currentUser endpoint on Engine (and it returns user data as expected)

Before doing more experiments (ie, running SDLC and Engine locally, and see if that solves the issue), could someone from the Legend team confirm that it is possible to run a Legend Studio instance in a local environment, but having SDLC and Engine on a remote server? Was this configuration ever tested?

Thanks in advance!

**Comment by akphi** [comment]
@maoo I see, the servers are remote. This would be caused by [SameSite cookie](https://web.dev/samesite-cookies-explained/). Chrome enabled this by default. So recommendation: you can try Firefox, or try to turn off the samesite check in Chrome

**Comment by maoo** [comment]
[From Shane]

Switching over to the Microsoft Edge browser fixed the problem we were experiencing! We are now able to use both our Kubernetes and remote Docker deployments to run studio on local host for development J Thanks for the help!

Thanks @akphi for your help! Closing issue.
