### ISSUE TITLE
Issue: Connectivity from Local studio to remote SLDC server.

### ISSUE THREAD

**Issue by AJ73** [finos/legend#472]
**Description**: We have set up legend backend applications on a shared dev server environment. It has all the applications( Gitlab, MongoDB,  SDLC and Engine) running.
We are trying to use our locally set up of Studio application to connect to the SLDC and Engine of the shared developer environment. **We are getting 401 Unauthorized error.**

As a solution we have set up the 

- updated the URLs on setup.js so it points to the remote dev server
- shared developer environment certificates on our local environment,
- also have used localhost & 127.0.0.1 in Gitlab callback

Please let us know if there is any particular configuration that needs to be set to set up the above environment. If there are any commonly followed steps for the similar kind of set up will help us. We have indeed done the usual cache clean, incognito etc.

cc: @pierredebelen ; @agitana  @beekemarie

**Comment by maoo** [comment]
Hi @AJ73 ! I did stumble on that few times, for different reasons.

I'll drop below few questions that helped me in the past with this (or similar) issues.

- Which version of Studio are you using?
- How are you deploying Legend? Docker Compose, Kubernetes, or from the source?
- Could you please share your Studio configuration file? It was updated in the past, so I'd like to make sure you're using the right one
- Did you authenticate against SDLC, before trying out Studio, using http://<host>:<sdlc port>/api/auth/authorize ? More info on https://github.com/finos/legend/blob/master/installers/docker-compose/legend-studio-dev/README.md . I suggest authenticating also against the engine component . You should be redirected to GitLab for authentication and get back a JSON file, which states the username of the currently logged in user
- Did you try to "Inspect Code" in your browser to identify the underlying call that is causing the issue? It may help debugging the issue
- Did you try using a different browser, such as Safari? Sometimes, Chrome plugins can affect Studio (and other JS apps)

HTH

**Comment by beekemarie** [comment]
@AJ73! Would be great if you could share some additional info with us (as indicated by @maoo above). Also adding @akphi to this thread.

**Comment by beekemarie** [comment]
Closing this issue as we haven't heard back from you @AJ73. Please feel free to re-open.
