### ISSUE TITLE
Depot URL configuration is not generated from the script

### ISSUE THREAD

**Issue by Mahvenu** [finos/legend#473]
### Steps to Reproduce:
 1. Deploy the latest version of the the docker-compose:
  finos/legend-studio:0.10.0 | finos/legend-engine-server:2.48.0 | finos/legend-sdlc-server:0.57.0
 2. After successful deployment, access the Studio application
 3. Studio fails to open.

### Expected Result:
Studio application should be successfully accessed.

### Actual Result:
Studio application is not working.

### Environment:
finos/legend-studio:0.10.0 | finos/legend-engine-server:2.48.0 | finos/legend-sdlc-server:0.57.0

### Additional Context:
I checked the browser console and the issue seems to be reading the Depot URL, when i checked the studio shared template, the uiConfig,yml has the below configuration:

"metadata": {
    "url": "__LEGEND_DEPOT_URL__/api"
  },

I replaced it with 
"depot": {
    "url": "http://<hostname>:9090/api"
  },

After replacing the application is working, but I am not sure what is the right URL value which needs to be used.
It would be great if the gen-config.sh script can be changed to handle this appropriately.

Thanks,
Mahesh V

**Comment by beekemarie** [comment]
Thanks @Mahvenu! @akphi & @epsstan - could you please take a look?

**Comment by akphi** [comment]
This must be from an older version of the `docker-compose` script. In the latest, we have changed it to a dummy value

https://github.com/finos/legend/blob/f3df20db28111e39ed648f4bd39ea4b6cdd245fe/installers/docker-compose/shared/templates/studio/uiConfig.json#L7-L9

I'm closing this issue.
