### ISSUE TITLE
GUI bug in Studio 2.3.0 when selecting a Connection

### ISSUE THREAD

**Issue by pierrelamy** [finos/legend#477]
### Steps to Reproduce:
 1. Click the connection link of an established connection in the Studio GUI
 
### Expected Result:
Access the connection configuration from the GUI by clicking on the left menu in the Studio GUI
![Screen Shot 2022-01-07 at 15 34 18](https://user-images.githubusercontent.com/22781393/148604104-05aa82fd-9d04-44f7-825f-71e313a8ce75.png)

### Actual Result:
We get ejected from the session when clicking the established Connection in the studio GUI.
To access the connection, we need to go through the textual view.  This is manageable, as we don't need to access the connection configuration very much.  The main issue is that the mapping link is just underneath it and we click the wrong link time to time, with unpleasant outcome as we lose any work that wouldn't have been sync'ed.  

### Environment:
Studio  2.3.0
SDLC 0.64.1
Engine 2.52.2

### Additional Context:
This issue didn't happen with the prior version that we were running (although it was an old one)

**Comment by beekemarie** [comment]
Thanks @pierrelamy! We will investigate and come back to you. I wasn't able to re-produce it just yet but will look into it further.

**Comment by MauricioUyaguari** [comment]
@pierrelamy  is this the issue on the connection with the username password authentication  ? This was fixed, we just need to do a release.

**Comment by akphi** [comment]
i.e. to test, you can use the `SNAPSHOT` Docker image of [finos/legend-studio:snapshot](https://hub.docker.com/r/finos/legend-studio/tags)

**Comment by pierrelamy** [comment]
Thanks for addressing the issue.  We'll look to confirm that it has been fixed once we upgrade the version.

**Comment by pierrelamy** [comment]
We updated to the Studio version 2.6.0 and confirmed that this issue has been addressed.  Thank you!
