### ISSUE TITLE
Provide the ability to wrap text in the Studio text mode + position the object definition before the associated description

### ISSUE THREAD

**Issue by pierrelamy** [finos/legend#478]
### Description of Problem:
The Studio text mode doesn't currently provide the ability to wrap text, which makes it use difficult.  Quite too often, we need to manually truncate the lines in order to have a comprehensive view of the code.
This problem is aggravated in the case of the model representation by the fact that the object is positioned after the associated definition, instead of beforehand.

### Potential Solutions:
1- Enable a text wrapping option, similar to the one available in most IDEs
2- Invert the positioning of the object name and associated definition in the text mode, as the object name is what matters the most

**Comment by beekemarie** [comment]
Thanks @pierrelamy! We will investigate and come back to you.

**Comment by akphi** [comment]
Text-wrapping has been implemented since https://github.com/finos/legend-studio/pull/584 so it should be available in the latest version. In the screenshot below, the button is on top-right corner.

![image](https://user-images.githubusercontent.com/13574879/148631034-624807a1-4159-4f5b-a448-3245cd0a698e.png)

Could you explain point (2) further? I don't think I get the idea there.

**Comment by pierrelamy** [comment]
I noticed the wrapping function as a follow-up from logging the issue.  This is a great improvement.  Many thanks!!
I do think that positioning the object definitions before the object description would further improve the usability of the textual browser.  Let me try to clarify. 
If you look at the below snippet, it is quite challenging to apprehend the model through the textual viewer because the class and attributes names aren't aligned as a result of the fact that they positioned at the end of the description fields.   When going through the model, you focus first and foremost on the object names.  This then means that you eye has to scroll the screen right and left to find those, which is very distracting and inefficient.
If those object names would instead be positioned before the description field, they would be vertically aligned on the left side of the screen, which would make it much easier to read.  This is the approach adopted in Rosetta, which is much more efficient IMO.  

![Screen Shot 2022-01-20 at 15 11 47](https://user-images.githubusercontent.com/22781393/150414778-c403d16c-fcec-4608-9275-eb554ca91338.png)
