### ISSUE TITLE
Feature request: Can we specify connection info when we execute a jar file instead of having it in the jar file?

### ISSUE THREAD

**Issue by waterfall49** [finos/legend#482]
### Similar requests

- [X] I have searched and found no existing similar requests

### What problems are you trying to solve?

- How to config DB connection when we use jar file as a library instead of having it in a jar file. 
- Reason: We don't want to have connection info in the jar file, would like to specify it later when we execute the jar file. 

### Describe the solution you would like to see implemented

For example, having a config file in which jar file can read info from it or having config inputs as a parameter so that we can specify it later. 

### Contribution

- [ ] I would like to work on this feature

**Comment by beekemarie** [comment]
Hey @MauricioUyaguari! Following up on this. Would you mind sharing your thoughts?

**Comment by MauricioUyaguari** [comment]
Yeah this is a feature request for legend-engine/legend-sdlc when generated the service jar. 
@[raf](https://github.com/rafaelbey) had made some adjustmented to the service jar making it more configurable.
Rafael could you share some of the adjustments you made to the service runner?

**Comment by rafaelbey** [comment]
@MauricioUyaguari - I think this is part of the changes @epsstan made to allow apps manage the identity and transforming these to DB credentials.  Let sync offline and collect the details.

**Comment by epsstan** [comment]
Closing this issue as it is the same as #502
