### ISSUE TITLE
We want to specify the connection info per each class or table when we execute jar file

### ISSUE THREAD

**Issue by waterfall49** [finos/legend#502]
### Description of Problem:
...what *problem* are you trying to solve that the project doesn't currently solve?
We created a relevant ticket previously (https://github.com/finos/legend/issues/482),
To extend the previous question, we want to specify the connection info per each class or table. 

...please resist the temptation to describe your request in terms of a solution.  Job Story form ("When [triggering condition], I want to [motivation/goal], so I can [outcome].") can help ensure you're expressing a problem statement.

### Potential Solutions:
...clearly and concisely describe what you want to happen. Add any considered drawbacks.
![image](https://user-images.githubusercontent.com/43071629/166555136-4e5bfc86-abe3-414c-b171-1f3003b20996.png)

... if you've considered alternatives, clearly and concisely describe those too.

**Comment by agitana** [comment]
Hi @waterfall49 the database details are sourced from the model connection runtime and used to make a database connection. See https://github.com/finos/legend/tree/service-exec-jar-example/examples/service-execution-jar and https://github.com/finos/legend/wiki/Database-Connectors---Configuration and let me know if you have further questions. / cc @beekemarie

**Comment by agitana** [comment]
Hi @waterfall49 the database details are sourced from the model connection runtime and used to make a database connection. See https://github.com/finos/legend/tree/service-exec-jar-example/examples/service-execution-jar and https://github.com/finos/legend/wiki/Database-Connectors---Configuration. 

You can additionally use multiple model stores backed by multiple databases, see https://github.com/finos/legend-engine/blob/b9c7618bf11aac64430082d6d0c2b13f5e6f5128/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/graphFetch/tests/testCrossStoreGraphFetch.pure and 

Let me know if you have further questions.

/ cc @beekemarie

**Comment by epsstan** [comment]
Closing this issue as a stale issue. Please re-open in the legend-engine repo if this is still relevant.
