### ISSUE TITLE
Issue with accessing the attribute details from the GUI

### ISSUE THREAD

**Issue by pierrelamy** [finos/legend#519]
## Bug Report
A bug has seemingly been introduced with the latest Studio version whereby it's not possible to access the attribute details from the GUI on previously opened attribute tabs.

### Steps to Reproduce:
 1. Select an attribute and click on the attribute details from the attribute tab: everything is fine.
 2. Open a new tab attribute and do the same: everything is fine
 3. Try to do the same on the previously opened tab attribute: doesn't work

### Environment:
legend-studio:                 6.6.0
legend-sdlc-server:         0.83.1
legend-engine-server:   3.9.2
[GUI Bug Report.pptx](https://github.com/finos/legend/files/9131675/GUI.Bug.Report.pptx)

**Comment by beekemarie** [comment]
Thanks for raising this bug, @pierrelamy! Adding the dev team to look into this.
