### ISSUE TITLE
https://legend.finos.org/docs/getting-started/maven-install.md ==> 404

### ISSUE THREAD

**Issue by saraswat** [finos/legend#524]
This link is on the [main installation page](https://legend.finos.org/docs/getting-started/installation-guide). 

```
Maven Install

This option is for software developers who want to build and run Legend from source. Instructions can be found [here](https://legend.finos.org/docs/getting-started/maven-install.md).
```

**Comment by akphi** [comment]
@saraswat Thanks for spotting this! We will fix this broken link. The Maven installation guide is right below so there's no need to click on that link to go anywhere
