### ISSUE TITLE
AWS Docker Install: broken link

### ISSUE THREAD

**Issue by simonletort** [finos/legend#529]
https://github.com/finos/legend/blob/669cb8aed00728d20fc1096d752d8bdb531a571e/docs/getting-started/installation-guide.md?plain=1#L99

````[here](aws-docker.md)```` is a [broken link](https://legend.finos.org/docs/getting-started/installation-guide#aws-docker-install),
suggestion to replace by ````[here](https://github.com/finos/legend/tree/master/installers/aws-docker)````

<img width="580" alt="Screen Shot 2022-08-10 at 7 12 19 AM" src="https://user-images.githubusercontent.com/367992/183897995-61eb0f42-f86c-46ec-97b8-4af53c73d4dc.png">

**Comment by epsstan** [comment]
Thanks for pointing this out.  We are refactoring the installers. The "AWS installer" will be deleted soon. You can follow the PR here https://github.com/finos/legend/pull/533

**Comment by simonletort** [comment]
👍
