### ISSUE TITLE
Difference between number, integer, and float in Legend Studio?

### ISSUE THREAD

**Issue by fmajorcminor** [finos/legend#544]
## Support Question

Not sure what the difference is between number and integer and float in Legend Studio. I'm seeing an option to mark a class property as integer, float, and also number. Is there a benefit / use case for picking number over the others?

**Comment by psancheti110** [comment]
Hi @fmajorcminor could you elaborate on the issue? 

also if this is not taken by anyone already I'd like to take this on. 

Thanks!

**Comment by finos-admin** [comment]
This issue was closed because it has been inactive for 35 days. Please re-open if this issue is still relevant.
