### ISSUE TITLE
Improve responsiveness of legend.finos.org website 

### ISSUE THREAD

**Issue by brooklynrob** [finos/legend#55]
The current version of alloy.finos.org does not degrade well, especially to mobile devices. It looks like the responsiveness that is there by default in both Docusaurus and the FINOS blueprint, may have gotten lost along the way, or just not included.

I think it's important the site render well on mobile and would suggest that work be undertaken to improve the sites responsiveness and how the site renders on the mobile devices. In particular the font gets so small on a mobile phone it's almost impossible to read the copy.

![25A42A95-9DE4-4978-A6DC-055644FCCAE4_1_102_o](https://user-images.githubusercontent.com/2136904/73960736-681c2700-48d9-11ea-98ec-f9685d5ab1ea.jpeg)

**Comment by gs-bracej** [comment]
The responsiveness is improved in my latest PR. I suspect there's still room for improvement, so will leave this open, but let's retest and comment on the specific places that need fixing.

**Comment by brooklynrob** [comment]
See too https://github.com/finos/alloy/issues/259 from @mindthegab

**Comment by aitana16** [comment]
legend.finos.org is now responsive on mobile
