### ISSUE TITLE
Getting the error - unable to find valid certification path to requested target - with docker-compose on windows

### ISSUE THREAD

**Issue by Mehul903** [finos/legend#654]
### Steps to Reproduce:
 1. Cloned finos/legend repo
 2. Edited the port for legend-studio in .env file from 9000 to 9003 
 3. Follow the steps to make it run via docker-compose
 4. Launch the application from any browser

### Expected Result:
Be able to use LEGEND Studio with all of its current features

### Actual Result:
I get this error: "HTTP ERROR 500 org.pac4j.core.exception.TechnicalException: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target"

### Environment:
Windows 10; docker version: 23.0.5

### Additional Context:
Also tried to add the gitlab certificate from browser into the java trust store, but that didn't solve the issue.

<img width="946" alt="legend-error" src="https://github.com/finos/legend/assets/18408662/2f0b5a29-4947-46e7-b1ce-53af2f5446c8">

Here's what I see when I launch docker-compose:
<img width="570" alt="legend-docker" src="https://github.com/finos/legend/assets/18408662/f11aeaf8-005f-4427-b53d-d8a61a2a24e4">

**Comment by finos-admin** [comment]
This issue was closed because it has been inactive for 35 days. Please re-open if this issue is still relevant.
