### ISSUE TITLE
'Failed to fetch' upon first time loading Legend

### ISSUE THREAD

**Issue by jim-doran** [finos/legend#657]
Upon following the steps detailed here: https://github.com/finos/legend/tree/master/installers/docker-compose, when attempting to access Studio for the first time at: http://localhost:9000/studio I am seeing warning saying 'Failed to Fetch' and then a continuous loading of the Legend screen. 
http://localhost:9000/ loads fine, where I am seeing the Legend logo, however upon trying to access Studio I see the above issue. 
Is there something I can do to resolve this? Have tried to rebuild the container package 10+ times.
Thanks.
![image](https://github.com/finos/legend/assets/125615947/eaebcff9-d579-44e3-a696-1ff3f902f171)

**Comment by jim-doran** [comment]
brought down and rebuilt container throughout the course of the weekend. same result
tried it Monday morning....success!

**Comment by uthali** [comment]
Hi.
I tried to re-install many times. I got same issue. How to resolve it?
