### ISSUE TITLE
Remove /docs from URL while keeping redirect to preserve current URLs

### ISSUE THREAD

**Issue by maoo** [finos/legend#67]
Right now, all `docs/` contents are rendered in `https://alloy.finos.org/docs/*`.

The docs prefix seems to be redundant, although standard within Docusaurus installations.

It is possible to get rid of the `docs` URL prefix using the `docsUrl` setting in `siteConfig.js` (see https://github.com/finos/open-developer-platform/commit/76ff9c9f139fb81369b300ca957bf6f5ca393e87 as example)

Using this feature would actually break any existing URL that uses the `docs/` prefix; to avoid that, we can create a redirect, following a similar approach to https://chillicream.com/blog/2018/11/07/docusaurus-docs-redirect ; it's not exactly the same case, but I think we can reuse some code.

Please stage the solution on a forked repository and provide a URL where the solution is staged.

**Comment by brooklynrob** [comment]
@maoo can we close this?

**Comment by maoo** [comment]
Yes, I think the docs/ URL prefix is actually helpful. @gs-bracej @beekemarie - feel free to reopen if you want to get rid of `docs/` from the site url.

**Comment by gs-bracej** [comment]
Yes I think the docs prefix is helpful too - it prevents conflicts with pilot instance URLs like /studio.
