### ISSUE TITLE
Running legend sdlc locally on https

### ISSUE THREAD

**Issue by shomil-maurya-db** [finos/legend#712]
Hi legend team,
For some reasons, our requirement is to run legend sdlc locally on https server. For this I installed cert and placed in my trust-store. I did following config change and getting this error.
![image](https://github.com/finos/legend/assets/112676561/a25ba2ab-1e0d-4a19-ac42-1a9e3abe3fcd)

![image](https://github.com/finos/legend/assets/112676561/f9d15dcd-4ef1-4769-b070-120159539314)

**Comment by akphi** [comment]
The error message seems like a good hint, please try to read through this and follow:
https://www.dropwizard.io/en/latest/manual/configuration.html#default

**Comment by shomil-maurya-db** [comment]
> The error message seems like a good hint, please try to read through this and follow: https://www.dropwizard.io/en/latest/manual/configuration.html#default

Hi @akphi, I did same config and running server with this command "java -jar C:/Users/maursho/LEGEND/legend-sdlc/legend-sdlc-server/target/legend-sdlc-server-0.91.2-SNAPSHOT-shaded.jar server C:/Users/maursho/LEGEND/legend-sdlc/legend-sdlc-server/src/test/resources/config-sample.yaml" , still same issue 
![image](https://github.com/finos/legend/assets/112676561/e5c0c181-f3c1-4168-a4fc-bc4d0e834fac)

**Comment by shomil-maurya-db** [comment]
> The error message seems like a good hint, please try to read through this and follow: https://www.dropwizard.io/en/latest/manual/configuration.html#default

Hi @akphi  @epsstan @beekemarie , this issue is resovled but while doing curl I am getting this error 
![image](https://github.com/finos/legend/assets/112676561/48a9445e-f650-4e03-b1b3-87ec96538692)
